ViewModels/EditRoleViewModel.cs
using EmployeeManagement.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EmployeeManagement.ViewModels
{
    public class EditRoleViewModel
    {
        public EditRoleViewModel()
        {
            Users = new List<ApplicationUser>();
        }
        public string RoleId { get; set; }

        [Required]
        [Display(Name ="Role Name")]
        public string RoleName { get; set; }

        public List<ApplicationUser> Users { get; set; }

    }
}

ViewModels/RoleViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EmployeeManagement.ViewModels
{
    public class RoleViewModel
    {
        [Required]
        [Display(Name = "Role Name")]
        public string RoleName { get; set; }
    }
}

Controllers/AdministrationController.cs
using EmployeeManagement.Models;
using EmployeeManagement.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace EmployeeManagement.Controllers
{
    public class AdministrationController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<ApplicationUser> userManager;

        public AdministrationController(RoleManager<IdentityRole> roleManager,UserManager<ApplicationUser> userManager)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
        }
        [HttpGet]
        public IActionResult CreateRole()
        {

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateRole(RoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                IdentityRole identityRole = new IdentityRole() { Name = model.RoleName };
                IdentityResult result = await roleManager.CreateAsync(identityRole);
                if (result.Succeeded)
                {
                    return RedirectToAction("roles", "administration");
                }
                foreach (IdentityError error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);

                }
            }

            return View(model);
        }
        [HttpGet]
        public IActionResult Roles()
        {
            return View(roleManager.Roles);
        }

        [HttpGet]
        public async Task<IActionResult> EditRole(string RoleId)
        {
            IdentityRole role = await roleManager.FindByIdAsync(RoleId);
            if (role == null)
            {
                return View("404NotFound", RoleId);
            }
            EditRoleViewModel roleVM = new EditRoleViewModel()
            {
                RoleId = role.Id,
                RoleName = role.Name,
            };
            foreach (var user  in userManager.Users)
            {
                if (await userManager.IsInRoleAsync(user,role.Name))
                {
                    roleVM.Users.Add(user);
                }
            }
            return View(roleVM);
        }

        [HttpPost]
        public async Task<IActionResult> EditRole(EditRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                IdentityRole role = await roleManager.FindByIdAsync(model.RoleId);
                if (role == null)
                {
                    return View("404NotFound", model.RoleId);
                }
                role.Name = model.RoleName;
                var result = await roleManager.UpdateAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("roles", "administration");
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> EditUsersInRole(string roleId)
        {
            ViewBag.roleId = roleId;

            var role = await roleManager.FindByIdAsync(roleId);

            if (role == null)
            {
                //ViewBag.ErrorMessage = $"Role with Id = {roleId} cannot be found";
                return View("CustomErrorPage",roleId);
            }

            var model = new List<UserRoleViewModel>();

            foreach (var user in userManager.Users)
            {
                var userRoleViewModel = new UserRoleViewModel
                {
                    UserId = user.Id,
                    UserName = user.UserName
                };

                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    userRoleViewModel.IsSelected = true;
                }
                else
                {
                    userRoleViewModel.IsSelected = false;
                }

                model.Add(userRoleViewModel);
            }

            return View(model);
        }
    }
}

Views/Administration/CreateRole.cshtml
@model RoleViewModel
@{
    ViewBag.Title = "CreateRole";

}

<h1>Create Role</h1>

<div class="row">
    <div class="col-md-12">
        <form  method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label class="form-label" asp-for="RoleName" ></label>
                <input class="form-control" asp-for="RoleName" />
                <span asp-validation-for="RoleName" class="text-danger"></span>
            </div>

            <button style="width:auto;" type="submit" class="btn btn-primary">Create Role</button>

        </form>

    </div>
</div>

Views/Administration/EditRole.cshtml
@model EditRoleViewModel

@{
    ViewBag.Title = "Edit Role";
}

<h1>Edit Role</h1>

<form method="post" class="mt-3">
    <div class="form-group row">
        <label asp-for="RoleId" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="RoleId" disabled class="form-control">
        </div>
    </div>
    <div class="form-group row">
        <label asp-for="RoleName" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="RoleName" class="form-control">
            <span asp-validation-for="RoleName" class="text-danger"></span>
        </div>
    </div>

    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">Update</button>
            <a asp-action="ListRoles" class="btn btn-primary">Cancel</a>
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            <h3>Users in this role</h3>
        </div>
        <div class="card-body">
            @if (Model.Users.Any())
            {
                foreach (var user in Model.Users)
                {
                    <h5 class="card-title">@user</h5>
                }
            }
            else
            {
                <h5 class="card-title">None at the moment</h5>
            }
        </div>
        <div class="card-footer">
            <a asp-action="EditUsersInRole" asp-controller="Administration" asp-route-roleId="@Model.RoleId" class="btn btn-primary" style="width:auto">Add or remove Users</a>
          
        </div>
    </div>
</form>

Views/Administration/EditUsersInRole.cshtml
@model List<UserRoleViewModel>

@{
    ViewData["Title"] = "EditUsersInRole";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var roleId = ViewBag.roleId;

}

<form method="post">
    <div class="card">
        <div class="card-header">
            <h2>Add or remove users from this role</h2>
        </div>
        <div class="card-body">
            @for (int i = 0; i < Model.Count; i++)
            {
                <div class="form-check m-1">
                    <input type="hidden" asp-for="@Model[i].UserId" />
                    <input type="hidden" asp-for="@Model[i].UserName" />
                    <input asp-for="@Model[i].IsSelected" class="form-check-input" />
                    <label class="form-check-label" asp-for="@Model[i].IsSelected">
                        @Model[i].UserName
                    </label>
                </div>
            }
        </div>
        <div class="card-footer">
            <input type="submit" value="Update" class="btn btn-primary" style="width:auto" />
            <a asp-action="EditRole" asp-route-id="@roleId"
               class="btn btn-primary" style="width:auto">Cancel</a>
        </div>
    </div>
</form>

Views/Administration/Roles.cshtml
@model IEnumerable<IdentityRole>
@{
    ViewData["Title"] = "Roles";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Roles</h1>

@if (Model.Any())
{
    <a asp-action="CreateRole" asp-controller="administration" class="btn btn-primary" style="width:auto">Add Role</a>
    foreach (var role in Model)
    {
        <div class="card mb-3">
            <div class="card-header">
                Role Id : @role.Id
            </div>
            <div class="card-body">
                <h5 class="card-title">@role.Name</h5>
            </div>
            <div class="card-footer">
                <a  class="btn btn-primary" asp-action="EditRole" asp-controller="administration" asp-route-RoleId="@role.Id">Edit</a>
                <a href="#" class="btn btn-danger">Delete</a>
            </div>
        </div>
    }
}
else
{
    <div class="card">
        <div class="card-header">
            No roles created yet
        </div>
        <div class="card-body">
            <h5 class="card-title">
                Use the button below to create a role
            </h5>
            <a class="btn btn-primary" style="width:auto"
               asp-controller="administration" asp-action="CreateRole">
                Create Role
            </a>
        </div>
    </div>
}